name: Deploy to Hetzner Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval $(ssh-agent)
          if [ -s ~/.ssh/deploy_key ]; then
            ssh-add ~/.ssh/deploy_key
            ssh-keyscan -H 5.161.62.246 >> ~/.ssh/known_hosts
          else
            echo "Private key is empty or not accessible"
            exit 1
          fi

      - name: Deploy to Hetzner
        run: ssh -o StrictHostKeyChecking=no root@5.161.62.246 "cd /var/www/lighteksystems.tech && git pull"

