name: Deploy to Hetzner Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Set up SSH
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_PASSPHRASE" | ssh-add ~/.ssh/id_rsa
          ssh-keyscan -t rsa 5.161.62.246 >> ~/.ssh/known_hosts

      - name: Deploy to Hetzner
        run: ssh -i ~/.ssh/id_rsa root@5.161.62.246 "cd /path/to/your/app && git pull"

